// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCUMIpNWnt_UqR_d5e5SPQG-6KqATfPoA',
    appId: '1:91374172570:web:d996bdbc661e7f4255e223',
    messagingSenderId: '91374172570',
    projectId: 'findr-b1753',
    authDomain: 'findr-b1753.firebaseapp.com',
    storageBucket: 'findr-b1753.firebasestorage.app',
    measurementId: 'G-NW33QS1C3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3SKb9lgpypG7NtN6YqFfi7INm5a4g3Co',
    appId: '1:91374172570:android:d36b3b4713d35d3a55e223',
    messagingSenderId: '91374172570',
    projectId: 'findr-b1753',
    storageBucket: 'findr-b1753.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpiikhpMxZ2RL7C_7nN40xU_tp1eOBHmU',
    appId: '1:91374172570:ios:2ea1a8dc71a01b7e55e223',
    messagingSenderId: '91374172570',
    projectId: 'findr-b1753',
    storageBucket: 'findr-b1753.firebasestorage.app',
    iosBundleId: 'com.example.findr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpiikhpMxZ2RL7C_7nN40xU_tp1eOBHmU',
    appId: '1:91374172570:ios:2ea1a8dc71a01b7e55e223',
    messagingSenderId: '91374172570',
    projectId: 'findr-b1753',
    storageBucket: 'findr-b1753.firebasestorage.app',
    iosBundleId: 'com.example.findr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCUMIpNWnt_UqR_d5e5SPQG-6KqATfPoA',
    appId: '1:91374172570:web:ff168351ab66d49e55e223',
    messagingSenderId: '91374172570',
    projectId: 'findr-b1753',
    authDomain: 'findr-b1753.firebaseapp.com',
    storageBucket: 'findr-b1753.firebasestorage.app',
    measurementId: 'G-9735R91XRS',
  );
}
